name: isaaclab
channels:
  - conda-forge
  - defaults

dependencies:
  # ---- conda packages ----
  - python=3.11.14
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zipp=3.23.0
  - zstd=1.5.7

  # ---- pip packages ----
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - anytree==2.13.0
      - asttokens==3.0.1
      - cloudpickle==3.1.2
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.83.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - comm==0.2.3
      - daqp==0.7.2
      - decorator==5.2.1
      - deepdiff==8.6.1
      - dex-retargeting==0.4.6
      - egl-probe==1.0.2
      - eigenpy==3.5.1
      - einops==0.8.1
      - evdev==1.9.2
      - executing==2.2.1
      - farama-notifications==0.0.4
      - feetech-servo-sdk==1.0.0
      - flaky==3.8.1
      - flatdict==4.0.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hidapi==0.14.0.post2
      - hpp-fcl==2.4.4
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isaaclab==0.53.0
      - isaaclab-assets==0.2.4
      - isaaclab-mimic==1.0.16
      - isaaclab-rl==0.4.7
      - isaaclab-tasks==0.11.12
      - jedi==0.19.2
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - junitparser==4.0.2
      - jupyterlab-widgets==3.0.16
      - leisaac==0.3.0
      - loop-rate-limiters==1.2.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - moviepy==2.2.1
      - msgpack==1.1.2
      - nlopt==2.7.1
      - omegaconf==2.3.0
      - onnx==1.20.1
      - onnx-ir==0.1.14
      - onnxscript==0.5.7
      - orderly-set==5.5.0
      - orjson==3.11.5
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pin==2.7.0
      - pin-pink==3.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - prettytable==3.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==6.33.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygame==2.6.1
      - pyglet==1.5.31
      - pygments==2.19.2
      - pynput==1.8.1
      - pyserial==3.5
      - pytest==9.0.2
      - pytest-mock==3.15.1
      - python-dotenv==1.2.1
      - python-xlib==0.33
      - pytransform3d==3.14.4
      - pyzmq==27.1.0
      - qpsolvers==4.8.2
      - quadprog==0.1.13
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2025.11.3
      - rich==14.2.0
      - rl-games==1.6.1
      - robomimic==0.4.0
      - rpds-py==0.30.0
      - rsl-rl-lib==3.1.2
      - safetensors==0.7.0
      - setproctitle==1.3.7
      - skrl==1.4.3
      - smmap==5.0.2
      - stable-baselines3==2.7.1
      - stack-data==0.6.3
      - starlette==0.49.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensordict==0.9.0
      - termcolor==3.3.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.3.0
      - tzdata==2025.3
      - wandb==0.23.1
      - warp-lang==1.11.0
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
